[package]
name = "opencv"
version = "0.1.0"
authors = ["trionprog <trionprog@gmail.com>"]
edition = "2018"

[dependencies]
futures = "0.1.29"
failure = "0.1.5"
failure_derive = "0.1.5"

opencv_sys = { version = "0.1.0", path = "../opencv_sys" }
libc = "0.2.0"